### ISSUE TITLE
npm install breakes on latest yosemite with latest node (v0.12.0)

### ISSUE THREAD

**Issue by edimoldovan** [justmoon/node-bignum#37]
Hi,

I updated node to latest on OS X and npm install fails finishing the install. I tried to put my npm-debug.log content in here, but it was too long. What should I paste of it so that it would help us find the issue?

This is the last lines of my console output, but there are a lot of other V8 errors shown. 

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.6.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.6.2 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/edimoldovan/www/project/server/npm-debug.log

And an example V8 error:

../bignum.cc:206:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Upowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments

Thanks,
Eduárd

**Comment by devlo** [comment]
I can confirm that. It's not working on node v0.12.0

**Comment by nikolay** [comment]
It's not been working for over 13 months on v0.11.x either.

**Comment by rvagg** [comment]
@nikolay stop being a troll. It's been working on 0.11 for a while now, those issues have just not been closed, updating to support 0.12 and io.js now.

**Comment by nikolay** [comment]
@rvagg Stop being overly sensitive and verbally vindictive. I found the old issue first (via googling) and then this. Since when providing feedback is trolling?

**Comment by rvagg** [comment]
Open source doesn't work when people like you parachute in and start moaning about problems you have zero background in just because a google search lead you here. The upgrade to 0.12 and io.js support was a simple 1-line change in package.json. If you can't be productive and contribute in material ways then your best contribution would be to stay silent.

**Comment by nikolay** [comment]
No need to patronize. I'm not using your project directly, but it broke my build thru another dependency and I reported the issue with them as well. Contribution to open-source project is solely via commits. Moaning or not, I possibly made you close a bunch of irrelevant tickets, i.e. I helped improve the status quo.

**Comment by edimoldovan** [comment]
@rvagg I did a nom install and I am getting the same error. Should I do anything what should I do to make it work?

**Comment by rvagg** [comment]
@edimoldovan `npm install bignum@latest` just to make sure you're getting 0.9.2. Also, perhaps you don't have the xcode command line tools installed? Do you know if you are able to compile any other native addons? If you don't know, perhaps try `npm install buffertools` and see how it goes.

Try `xcode-select -p` and see if it comes back with anything interesting, it'll print `/Applications/Xcode.app/Contents/Developer` if you have the full XCode installed.

If you type `gcc` and it gives you some interesting output then that's a good sign. If it brings up a dialog then it should give you a chance to install the commandline tools. You should also be able to run `xcode-select --install` to trigger an install I think.

**Comment by edimoldovan** [comment]
@rvagg xcode and pals was fine, there was a 0.6.2 dependency in dulcimer which broke the install. On the other hand, there are a lot of other modules which break, some I don’t know why, some I can fix with version bumps. My solution was to get back to node v0.10.36 because I was unable to work on my projects.

But the new version of bignum is fine with latest stable node, thanks a lot for that.

**Comment by scottie** [comment]
same issue here ?
