### ISSUE TITLE
cannot build in node version 0.11.10

### ISSUE THREAD

**Issue by nim23** [justmoon/node-bignum#24]
npm http GET https://registry.npmjs.org/bignum
npm http 304 https://registry.npmjs.org/bignum

> bignum@0.6.2 install /Users/nimeshgurung/Desktop/api-node/node_modules/bignum
> node-gyp configure build

  CXX(target) Release/obj.target/bignum/bignum.o
../bignum.cc:172:16: error: expected class name
class BigNum : ObjectWrap {
               ^
../bignum.cc:189:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:190:39: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> ToString(const Arguments& args);
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:191:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Badd(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:192:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bsub(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:193:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bmul(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:194:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bdiv(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:195:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Uadd(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:196:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Usub(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:197:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Umul(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:198:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Udiv(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:199:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Umul_2exp(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:200:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Udiv_2exp(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:201:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Babs(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:202:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bneg(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:203:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bmod(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:204:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Umod(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:205:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bpowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:206:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Upowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/nimeshgurung/.node-gyp/0.11.10/deps/v8/include/v8.h:141:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:862:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/nimeshgurung/Desktop/api-node/node_modules/bignum
gyp ERR! node -v v0.11.10
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm ERR! bignum@0.6.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.6.2 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bignum"
npm ERR! cwd /Users/nimeshgurung/Desktop/api-node
npm ERR! node -v v0.11.10
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nimeshgurung/Desktop/api-node/npm-debug.log
npm ERR! not ok code 0

**Comment by nikolay** [comment]
Same error for v0.12.00, which is the latest stable! Can't believe this has been open for 13 months!

**Comment by rvagg** [comment]
Yeah, it's amazing that someone filed an issue without anyone submitting a patch and this is _still_ open! Open source, how does it work?

**Comment by Meekohi** [comment]
lol ;D
